name: Main Workflow
on:
  workflow_dispatch:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
          5.0.x
        include-prerelease: true

    - name: Install JetBrains dotCover
      run: dotnet tool install JetBrains.dotCover.GlobalTool --global

    - name: Build QuantLib DLL
      run: dotnet build ./QuantLib/QuantLib.csproj --verbosity normal --configuration Release --nologo 

    - name: Build Quantower charts DLL
      run: dotnet build ./Quantower_charts/Quantower.csproj --verbosity normal --configuration Release --nologo 

    - name: Test with dotnet
      run: dotnet test ./Tests/Tests.csproj --verbosity normal --configuration Release --nologo 

    - name: Test with dotCover
      run: dotnet dotcover test ./Tests/Tests.csproj --verbosity normal --framework net7.0 --dcReportType=DetailedXML --dcoutput=Tests/coveragereport.xml

    - name: CodeCov installation
      run: dotnet tool install --global Codecov.Tool

    - name: CodeCov run
      run: codecov -f ./Tests/coveragereport.xml -v -t ${{ secrets.CODECOV_TOKEN }}

    - name: Codacy coverage reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./Tests/coveragereport.xml

